admins:
- admin
static_users:
- username: User-a
  password: pass-a
  tenants:
  - tenant-a
- username: User-b
  password: pass-b
  tenants:
  - tenant-b
- username: admin
  password: admin
  tenants:
  - admin
